### ISSUE TITLE
BUG: Axis compute in absolute terms

### ISSUE THREAD

**Issue by cpelley** [SciTools-incubator/python-stratify#14]
I originally put up a PR with iris [here](https://github.com/SciTools/iris/pull/2532) relating to tests which failed for me.
Now that I'm looking at the stratify implementation itself, I think I see a bug here in the checks conducted on the axis term which I suspect is where the real problem resides.

```Python
        # Compute the axis in absolute terms.
        fp_axis = (axis + fz_src.ndim) % fz_src.ndim
        zp_axis = fp_axis - (fz_src.ndim - z_src.ndim)
        if not 0 <= zp_axis < z_src.ndim or axis > z_src.ndim:
            raise ValueError('Axis {} out of range.'.format(axis))
```

[_Interpolation.\_\_init\_\_ here](https://github.com/SciTools-incubator/python-stratify/blob/12a556afe30880b1ba175afeaed6d2e78431f468/stratify/_vinterp.pyx#L551)

Specifically `axis > z_src.ndim` must be wrong surely??  `axis` is relative to `fz_src` not `z_src`.  To make this check valid, instead I would expect to see `zp_axis > z_src.ndim`.

I'm more than happy with fixing this myself if confirmed as a bug :)

**Comment by cpelley** [comment]
Can you confirm this @pelson?

Thanks :)

**Comment by cpelley** [comment]
P.S. support for negative axis in this way is neat and awesome (fp_axis)

**Comment by pelson** [comment]
Sure looks like it! Thanks @cpelley.
