### ISSUE TITLE
Releasing v0.1

### ISSUE THREAD

**Issue by pelson** [SciTools-incubator/python-stratify#19]
I think we are good to go with a v0.1 release.

@cpelley would you mind doing the honours?

Steps:
 - [x] bump the version in the repo (or submit a PR to use versioneer 😉 )
 - [x] tag on github
 - [x] push up to pypi (https://pypi.python.org/pypi/stratify/)
 - [x] bump the version in the repo to v0.2dev0

**Comment by cpelley** [comment]
Sure, I'm having trouble with uploading to pypi.

I don't have permissions to update it:
`The user 'cpelley' is not allowed to upload to project 'stratify'`

Secondly, to make the upload not fall over I have to replace:

```
        ('License :: OSI Approved :: '
'License :: OSI Approved :: BSD License'),
```

with

```
    'License :: OSI Approved :: BSD License'
```
In setup.py  What's the context of the dummy license line?

**Comment by pelson** [comment]
@cpelley - that line clearly needs to be fixed! 😄

**Comment by pelson** [comment]
You should have maintainer permissions on pypi for stratify now.

**Comment by cpelley** [comment]
Thanks Phil.  I assume I should replace the tag release with a fixed one? (I think replacing makes sense given that pypi won't be able to install the exiting tag release)

**Comment by cpelley** [comment]
Let's just fix on master and upload the existing tag release with that locally fixed for the purpose of the package upload to pypi.

EDIT: Applied the [fix](https://github.com/SciTools-incubator/python-stratify/commit/61b2d0a4586ad3fb890474357ed65a0c4a69b22a) to master directly.

**Comment by cpelley** [comment]
- [ ] Updading [python-stratify-feedstock](https://github.com/conda-forge/python-stratify-feedstock).

**Comment by bjlittle** [comment]
Awesome work @cpelley, thanks!
