### ISSUE TITLE
Installation from PyPI fails

### ISSUE THREAD

**Issue by bouweandela** [SciTools-incubator/python-stratify#25]
Trying to install from PyPI without first installing Cython fails:
```
Collecting stratify (from ESMValTool==2.0a1)
  Downloading https://files.pythonhosted.org/packages/f9/a6/067946d74affbd4bb1130f157f7be6b9f8ce6be56d8eb694cffce9b53e19/stratify-0.1.tar.gz (231kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-492vc9kg/stratify/setup.py", line 8, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
```

**Comment by bjlittle** [comment]
Ping @bouweandela - closed by https://github.com/SciTools-incubator/python-stratify/pull/29

I'll be tagging a patch release and updating PyPI and conda-forge with the fix :smile:

**Comment by bjlittle** [comment]
Hey @bouweandela... The latest `python-stratify` version `0.1.1` which addresses this issue is now available on `conda-forge` and `PyPI` :wink:
