### ISSUE TITLE
PyPI tar file misses *.pyx file, causing `pip install python-stratify` to fail

### ISSUE THREAD

**Issue by evertrol** [SciTools-incubator/python-stratify#26]
Installation through PyPI (e.g., using `pip`) may fail when a wheel is not available. Pip will attempt to download and untar the file from PyPI, then build the project. Even with Cython available (i.e., this issue is independent of #25), the project can't be build, because of its dependence on the relevant `*.pyx` files: the C-files by themselves are not enough to automatically build the project with the current `setup.py`.

My guess is that either
- `setup.py` needs to include the `*.c` files directly, and not the `*.pyx` (nor "cythonize" them; this would also fix #25)
- the `*.pyx` need to be included instead of the `*.c` files

to fix this issue.

**Comment by bjlittle** [comment]
@evertrol Thanks for raising this.

Okay time to address these related installation issues...

**Comment by bjlittle** [comment]
Ping @evertrol - closed by https://github.com/SciTools-incubator/python-stratify/pull/29

I'll be tagging a patch release and updating PyPI and conda-forge with the fix :smile:

**Comment by bjlittle** [comment]
@evertrol The latest `python-stratify` version `0.1.1` which addresses this issue is now available on `conda-forge` and `PyPI`
