### ISSUE TITLE
Support for dask arrays

### ISSUE THREAD

**Issue by bouweandela** [SciTools-incubator/python-stratify#39]
Because the datasets we use with the [ESMValTool project](https://github.com/ESMValGroup) are typically too large to fit into memory, we need support for lazy vertical interpolation in the ESMValCore package, see also https://github.com/ESMValGroup/ESMValCore/issues/35.

Would support for dask arrays be a feature that is interesting for python-stratify? I think it could be used by a wider target audience if it's implemented here than if we only implement it for our own software. If there is an interest, I could make a pull request to add support for dask arrays to this package?

**Comment by bjlittle** [comment]
@bouweandela Sorry I'm late to the party, but if this is still of value to you guys and have capacity, then please do extend `python-stratify` to cope with `dask` arrays... that would be a definite community win for sure :+1: 

Awesome, thanks!
