### ISSUE TITLE
Remove cython from install_requires

### ISSUE THREAD

**Issue by zklaus** [SciTools-incubator/python-stratify#40]
Having cython in `install_requires` creates a problem down the line in the conda-forge package, which does not carry cython as a runtime dependency, which in turn leads entry_point resolution in downstream packages to a failure.

Of course, one solution is to add cython as a runtime dependency to the conda-forge package, but I am wondering if cython is actually needed as a runtime dependency. Isn't it enough to have it in `setup_requires`?

**Comment by zklaus** [comment]
@bjlittle, what's your take on this?

**Comment by bjlittle** [comment]
@zklaus Sorry, I'm super late to this... :blush: 

The `install_requires` is there for `pip` really... how are you hitting this problem through `conda`? Just curious. I'm not really understanding the context of the problem

**Comment by ocefpaf** [comment]
For pip, or any other Python packaging, I guess you only need `setup_requires`. When you add it to `install_requires` it becomes a run time dependency and `pip check` will fail if you don't have it installed. It is not really a conda issue, we only catch it b/c we run `pip check` in our CIs.

**Comment by bjlittle** [comment]
@zklaus Okay, I'm going to address this today, and push another release of `python-stratify` :+1:

**Comment by zklaus** [comment]
Thanks @bjlittle, and no worries. To add to what @ocefpaf said, when using entry_points this check now happens automatically on running a program. That may be a relatively recent change since entry points now use importlib_metadata instead of pkg_resources by default at least on python 3.8, but here we are. Basically, on every run of a program as a first step all declared runtime dependencies are checked, regardless of whether they are actually used.

**Comment by bjlittle** [comment]
@zklaus Ahhh okay, lovely thanks, now I finally understand the context of what you were originally saying... thanks for clarifying.

Much appreciated :beers:

**Comment by bjlittle** [comment]
Closed by #41
